stages:
  - build
  - validate
  - publish 

variables:
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  SYFT_VERSION: "v1.3.0"
  GRYPE_VERSION: "v0.77.2"

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'pipelines/go-build.yml'
      - 'pipelines/linter.yml'
