stages:
  - build

variables:
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"

build_go:
  stage: deploy
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/go-build.yml'
  rules:
      exists:
      - "go.mod"  
