stages:
  - compliance
  - deploy

variables:
  GO_VERSION: "1.20"
  GOLANGCI_LINT_VERISON: "v1.55.2"

gitlab_generic_package:
  stage: deploy
  needs: 
    - job: compliance
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/gitlab_generic_packages.yml'
  rules:
    - if: '$PIPELINE =~ /gitlab/'

build_go_api:
  stage: deploy
  needs: 
    - job: compliance
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/golang.yml'
  rules:
    - exists:
      - "go.mod"  
