stages:
  - deploy

variables:
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  UPLOAD_PACKAGE: "false"

build_go:
  stage: deploy
  allow_failure: false
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/go-build.yml'
    strategy: depend
  rules:
    - exists:
      - "go.mod"  
