stages:
  - compliance
  - deploy

variables:
  GO_VERSION: "1.22"
  GOLANGCI_LINT_VERISON: "v1.58.0"
  SYFT_VERSION: "v1.3.0"
  GRYPE_VERSION: "v0.77.2"

gitlab_generic_package:
  stage: deploy
  needs: 
    - job: compliance
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/gitlab_generic_packages.yml'
  rules:
    - if: '$PIPELINE =~ /gitlab/'

build_go:
  stage: deploy
    #needs: 
    #  - job: compliance
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/golang.yml'
  rules:
    - exists:
      - "go.mod"  
