stages:
  - compliance
  - deploy

compliance:
  stage: compliance
  strategy: depend
  trigger:
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/compliance.yml'


gitlab_generic_package:
  stage: deploy
  needs: 
    - job: compliance
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/gitlab_generic_packages.yml'
  rules:
    - if: '$PIPELINE =~ /gitlab/'
