gitlab_generic_package:
  trigger: 
    include: 
    - project: 'developerdurp/yml'
      ref: 'main'
      file:
        - 'pipelines/gitlab_generic_packages.yml'
  rules:
    - if: '$PIPELINE =~ /gitlab/'
