stages:
  - build
build-container:
  image: docker:20.10.16
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:20.10.16-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  stage: build
  script:
    # Begin of docker-login.sh
    - |
      #login to docker
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY/$CI_PROJECT_PATH
    # End of docker-login.sh

    # Begin of docker-build.sh
    - |
      #Build Docker Container
      docker build -t "$CI_REGISTRY/$CI_PROJECT_PATH:latest" .
      docker push "$CI_REGISTRY/$CI_PROJECT_PATH:latest"
    # End of docker-build.sh
  only:
    - main

