stages:
  - build
build-container:
  image: docker:20.10.16
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:20.10.16-dind
  stage: build
  script:
    # Begin of docker-login.sh
    - |
      #login to docker
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY/$CI_PROJECT_PATH
    # End of docker-login.sh

    # Begin of docker-build.sh
    - |
      #Build Docker Container
      docker build -t "$CI_REGISTRY/$CI_PROJECT_PATH:latest" .
      docker push "$CI_REGISTRY/$CI_PROJECT_PATH:latest"
    # End of docker-build.sh
  only:
    - main

