stages:
  - build
  - package
  - publish

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/docker.yml'
      - 'jobs/version.yml'

secret_detection:
  stage: .pre
  rules:
    - when: always
  allow_failure: false

version:
  extends: .version
  stage: .pre
  rules:
    - when: always

build_container: 
  extends: .docker_build
  stage: build
  artifacts:
    paths:
     - $CI_PROJECT_DIR/package
  needs: 
    - job: version
      artifacts: true

upload_container:
  extends: .docker_push_gitlab
  stage: package
  needs: 
    - job: version
      artifacts: true
    - job: build_container
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
    - if: $CI_COMMIT_BRANCH =~ 'main'
    - when: never
