stages:
  - build
  - validate
  - publish 

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/golang.yml'
      - 'jobs/version.yml'
      - 'jobs/golang.yml'
      - 'jobs/docker.yml'
      - 'rules/rules.yml'
      - 'pipelines/templates/security.yml'


        #version:
        #  extends: .version
        #  stage: .pre
        #  rules:
        #    - !reference [.default_rules, rules]

golang-lint:
  extends: .golang-lint
  stage: validate
  rules:
    - !reference [.mr_only_rules, rules]

docker-build:
  extends: .docker_build
  stage: build
  needs:
    - job: gobuild
      artifacts: true
        #- job: version
        #  optional: true
        #  artifacts: true        
  rules:
    - !reference [.docker_rules, rules]

gobuild:
  variables:
    GOPROXY: https://nexus.durp.info/repository/go/
  extends: .golang-build
  stage: build
  rules:
    - !reference [.default_mr_rules, rules]

docker-push:
  extends: .docker_push_gitlab
  stage: publish
  needs:
    - job: gobuild
      artifacts: true
        #- job: version
        #  artifacts: true        
  rules:
    - !reference [.docker_publish_rules, rules]
