stages:
  - build
  - validate
  - publish 

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/golang.yml'
      - 'pipelines/compliance.yml'
      - 'pipelines/go-build.yml'
      - 'pipelines/docker-build.yml'
      - 'pipelines/linter.yml'
      - 'pipelines/security.yml'
      - 'rules/rules.yml'

gobuild:
  variables:
    GOPROXY: https://nexus.durp.info/repository/go/
  extends: .golang-build
  stage: build
  rules:
    - !reference [.default_mr_rules, rules]

