stages:
  - build

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/golang.yml'

gobuild:
  variables:
    GOPROXY: https://nexus.durp.info/repository/go/
  extends: .golang-build
  stage: build
  rules:
    - !reference [.default_mr_rules, rules]
      exists:
        - "go.mod"  

