stages:
  - build
  - package
  - publish 

include:
  - project: 'developerdurp/yml'
    ref: main
    file: 
      - 'jobs/version.yml'
      - 'jobs/sonarqube.yml'
      - 'jobs/docker.yml'
      - 'jobs/helm.yml'

version:
  extends: .version
  stage: .pre
  only:
    - main

sonarqube:
  extends: .sonarcloud-check
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' || $CI_PIPELINE_SOURCE == 'merge_request_event'

gobuild:
  extends: .version
  stage: build

docker:
  extends: .docker-build-container
  stage: publish
  needs:
    - job: gobuild
      artifacts: true  
  only:
    - main

helm:
  extends: .helm-createchart
  stage: publish
  only:
    - main 