stages:
  - build
  - package
  - publish 

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/version.yml'
      - 'jobs/sonarqube.yml'
      - 'jobs/golang.yml'
      - 'jobs/docker.yml'

version:
  extends: .version
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'

sonarqube:
  extends: .sonarcloud-check
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' || $CI_PIPELINE_SOURCE == 'merge_request_event'

golang-lint:
  extends: .golang-lint
  stage: .pre

gobuild:
  variables:
    GOPROXY: https://nexus.durp.info/repository/go/
  extends: .golang-build-api
  stage: build

docker:
  extends: .docker-build-container
  stage: publish
  needs:
    - job: gobuild
      artifacts: true
    - job: version
      artifacts: true        
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'

