stages:
  - build
  - package
  - validate
  - publish 

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/octopus.yml'
      - 'jobs/version.yml'
      - 'jobs/sonarqube.yml'
      - 'jobs/golang.yml'
      - 'jobs/docker.yml'

version:
  extends: .version
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'

gobuild:
  variables:
    GOPROXY: https://nexus.durp.info/repository/go/
  extends: .golang-build
  stage: build

docker-build:
  extends: .docker_build
  stage: build
  needs:
    - job: gobuild
      artifacts: true
    - job: version
      optional: true
      artifacts: true        
  rules:
    - exists:
      - "Dockerfile"  

docker:
  extends: .docker_push_gitlab
  stage: publish
  needs:
    - job: gobuild
      artifacts: true
    - job: version
      artifacts: true        
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      exists:
        - "Dockerfile"  
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
      exists:
        - "Dockerfile"  
