stages:
  - build  
  - publish 

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/version.yml'
      - 'jobs/helm.yml'

version:
  extends: .version
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'

helm-build:
  extends: .helm-build
  stage: build
  needs:
    - job: version
      artifacts: true      
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'

helm-push:
  extends: .helm-push
  stage: publish
  needs:
    - job: helm-build
      artifacts: true
    - job: version
      artifacts: true      
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
    - if: $CI_COMMIT_BRANCH =~ '/^release/'
