stages:
  - package
  - publish 

include:
  - project: 'developerdurp/yml'
    ref: main
    file: 
      - 'jobs/version.yml'
      - 'jobs/octopus.yml'


version:
  extends: .version
  stage: .pre
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'

pack:
  variables:
    WORKDIR: $CI_PROJECT_DIR
  extends: .octo_package
  stage: package
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'