stages:
  - build

include:
  - project: 'developerdurp/yml'
    ref: 'main'
    file: 
      - 'jobs/codescan.yml'

generate_sbom:
  extends: .generate_sbom
  stage: build
  needs:
    - job: docker-build
      optional: true
      artifacts: true
  rules:
    - !reference [.default_mr_rules, rules]

generate_cve:
  extends: .generate_cve
  stage: build
  needs:
    - job: generate_sbom
      artifacts: true
  rules:
    - !reference [.default_mr_rules, rules]
