stages:
  - plan
  - apply
  - destroy

variables:
  WORKDIR: $CI_PROJECT_DIR/.tf
  GITLAB_TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/gitlab
  TF_VAR_GITLAB_PROJECT_ID: $CI_PROJECT_ID
  TF_VAR_GITLAB_PROJECT_NAME: $CI_PROJECT_NAME
  TF_VAR_GITLAB_TOKEN: $CI_JOB_TOKEN

image:
  name: registry.durp.info/hashicorp/terraform:light
  #name: hashicorp/terraform:light
  entrypoint: [""]

include:
  - project: 'developerdurp/yml'
    ref: main
    file: 
      - 'jobs/terraform.yml'

format:
  stage: .pre
  allow_failure: false
  extends: .terraform_fmt

validate:
  stage: .pre
  allow_failure: false
  extends: .terraform_validate

apply:
  stage: apply
  allow_failure: false
  extends: .terraform_apply   
  rules:
    - when: manual
