stages:
  - plan
  - apply
  - destroy

variables:
  WORKDIR: $CI_PROJECT_DIR/terraform
  GITLAB_TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${ENVIRONMENT_NAME}  

image:
  name: registry.durp.info/hashicorp/terraform:light
  #name: hashicorp/terraform:light
  entrypoint: [""]

include:
  - project: 'developerdurp/yml'
    ref: main
    file: 
      - 'jobs/terraform.yml'

format:
  stage: .pre
  allow_failure: false
  extends: .terraform_fmt

validate:
  stage: .pre
  allow_failure: false
  extends: .terraform_validate

plan:
  stage: plan
  allow_failure: false
  extends: .terraform_plan
  needs: ["validate","format"]  

apply:
  stage: apply
  allow_failure: false
  extends: .terraform_apply   
  rules:
    - when: manual
