stages:
  - build  

build-container:
  image: docker:19.03.12
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - ./scripts/docker-login.sh
    - ./scripts/docker-build.sh
  only:
    - main